### ISSUE TITLE
broken output for figures with spaces in filenames

### ISSUE THREAD

**Issue by danomatika** [tomduck/pandoc-fignos#23]
EDIT: I'm on OS X & pandoc is installed via homebrew

I recently updated to pandoc 1.17.2 & pandoc-fignos master and notice that figures with spaces in their filenames are now broken.

The following markdown:

```
![(left) _Schotter_ Georg Nees 1969 (right) _Olympiad_ Lillian Schwartz 1971](figures/collaboration/Schotter and Olympiad.png){#fig:Schotter-Olympiad}
```

is generated into html:

```
<figure>
<img src="figures/collaboration/Schotter" alt="(left) Schotter Georg Nees 1969 (right) Olympiad  Lillian Schwartz 1971" id="fig:Schotter-Olympiad" /><figcaption>(left) <em>Schotter</em> Georg Nees 1969 (right) <em>Olympiad</em> Lillian Schwartz 1971</figcaption>
</figure>
```

and generating a pdf leads to errors:

```
pandoc: Could not find image `figures/collaboration/Schotter', skipping...
```

Clearly the spaces are currently not propagating through the filter. This was working fine a year ago.

As a test, I removed `--filter pandoc-fignos` from my pandoc build line and the images are linked correctly.

**Comment by tomduck** [comment]
Thanks for the feedback.  I can confirm that this is an issue and will work on a fix.  It looks like the problem began with pandoc-1.16.  With pandoc-1.15 everything still works fine.

**Comment by tomduck** [comment]
I found and corrected the bug in the `nextrelease` branch.  Would you mind testing it?  If everything is OK then I will put out a new release.

**Comment by danomatika** [comment]
Working for html output. I'm getting the following when generating a pdf:

```
! LaTeX Error: Environment no-prefix-figure-caption undefined.
```

**Comment by tomduck** [comment]
OK, thanks.  I will run some more tests.

**Comment by tomduck** [comment]
I forgot to require the latest version of `pandoc-xnos` in `setup.py`. It was already installed on my machine which is why I missed it.  Duh.

If you could test the `nextrelease` branch again I would appreciate it.  Please make sure that `pandoc-xnos 0.4.1` installs with `pandoc-fignos`.

**Comment by tomduck** [comment]
I decided to push out a new version to pypi.  So, you can install using `pip` if you want.

**Comment by danomatika** [comment]
I'm still seeing the same issue (no-prefix-figure-caption undefined) with pandoc-fignos 0.16 & pandoc-xnos 0.4.1. I'm building & install both manually using setup.py.

**Comment by tomduck** [comment]
Sorry for the long delay, @danomatika: I have been swamped for the past few months.  I have just pushed some fixes to the `newrelease` branch.  There was an edge case I didn't see before that resulted in a `no-prefix-figure-caption` crash.  If it is still of interest, I would appreciate knowing if it fixes the problem you were having.

**Comment by danomatika** [comment]
Updated to latest next release branches of pandoc-fignos & pandoc-xnos. Using pandoc 1.17.2.

Still see the same error:

```
! LaTeX Error: Environment no-prefix-figure-caption undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.371 \begin{no-prefix-figure-caption}

pandoc: Error producing PDF
make: *** [pdf] Error 43
```

I double checked and it doesn't seem like `no-prefix-figure-caption` is defined in the pandoc latex template. Is this something specific to pandoc-fignos or is my tex install missing something?

**Comment by tomduck** [comment]
Thanks, @danomatika.  Can you please provide me with a minimum non-working example (markdown and build command)?  I will see if I can reproduce the same behaviour here.

**Comment by tomduck** [comment]
... and in answer to your question: `no-prefix-figure-caption` is specific to pandoc-fignos.  It is a custom TeX macro that disables figure prefixes.  For some reason the macro definition isn't getting written, which is why you see the error.

**Comment by danomatika** [comment]
I have a test paper and, of course, I can't trigger the bug. I'm seeing the macro definition in the raw .tex output... will keep digging.

**Comment by danomatika** [comment]
Ok, found it.

The xnos & fignos macros are _not_ added to the tex output if the abstract YAML metadata is set with multiple lines aka:

```
abstract: |
  Hello World ....
```

Maybe this is a bug in pandoc.

Here's a simple test project that causes the bug: [fignos-test.zip](https://github.com/tomduck/pandoc-fignos/files/523188/fignos-test.zip)

Main usage: `make pdf`, `make html`, & `make tex`

**Comment by tomduck** [comment]
Hi @danomatika: Can you possibly post these files in plaintext?  I can't unpack the zip.  Thanks.

**Comment by tomduck** [comment]
Aha!  I see the problem.  With multi-line YAML, pandoc-fignos incorrectly inserts its TeX into the json metadata.

**Comment by tomduck** [comment]
@danomatika: I made changes to the pandoc-XNOS `nextrelease` branch.  Can you please give it a try?

I modified the xnos code to avoid walking the meta tree during the TeX insertion process.  It fixes the bug on my end.  Hopefully yours too. :o)

**Comment by danomatika** [comment]
Yup, that fixed it. I updated box xnos & fignos to lasts commits in `nextrelease` branch.

**Comment by tomduck** [comment]
FANTASTIC.  Thanks for your help and patience, @danomatika.

**Comment by danomatika** [comment]
Thanks! Glad we _figured_ it out. (hah)

**Comment by tomduck** [comment]
LOL.  :o)  The new version is finally pushed out.  Cheers!
