### ISSUE TITLE
Why is "xnos-number-sections" limited to format html?

### ISSUE THREAD

**Issue by gepcel** [tomduck/pandoc-fignos#59]
I like the "xnos-number-sections", but it only works in a format of html or html5. Is there any specific reason? 

I want to use it in word output, and I've tested it by deleting some `if fmt in ['html', 'html5']`, it works. If it's ok with you, I can make a pull request.

**Comment by melaniewalsh** [comment]
Just wanted to second this request for section number support for Word documents. It'd be great if one of these pull requests could be integrated. Thanks!

**Comment by gepcel** [comment]
@melaniewalsh, It's just small changes, I suggest you do it manually.

**Comment by tomduck** [comment]
Hello @gepcel and @melaniewalsh.  Sorry for the long delay owing to a busy time at work.  I'm going to update pandoc-fignos for the new pandoc releases and get back to you.

**Comment by tomduck** [comment]
Can I have some more information on how you are using this feature?  The `xnos-number-sections` variable is meant to be used together with pandoc's `--number-sections` flag.  The pandoc manual says this flag only numbers sections in LaTeX, ConTeXt, HTML, or EPUB output -- not docx.  Are your sections being numbered by hand instead?  Thanks.

**Comment by gepcel** [comment]
@tomduck Oh, I didn't know about the pandoc manual. As for how I use this feature. For example, a txt file like (I'm using [markdown-preview-enhanced](https://atom.io/packages/markdown-preview-enhanced) with atom, it's basicly converting the following contents to word, with the style.docx as template, using the pandoc-fignos filter with "xnos-number-sections" set to be True):

```markdown
---
output:
  word_document:
    reference_doc: c:/python/lib/style.docx
    pandoc_args: [
    '--filter=pandoc-fignos'
    ]
xnos-number-sections: True
---

# first chapter

Contents of chapter 1

# Second chapter

Contents of chapter, +@fig:fig_id

![fig_Caption](file.png){#fig:fig_id}

```

And got the following word (attached later):
![image](https://user-images.githubusercontent.com/4179106/57417078-aba41080-7235-11e9-9fbe-e8a2763b69b3.png)

Note that the "Figure 2-1" instead of the "Fig 2.1" was the result for my needs. If you are instrest, check  the [folk](https://github.com/gepcel/pandoc-fignos/tree/caption_sep), ignore it if not.

The result doc: [result.docx](https://github.com/tomduck/pandoc-fignos/files/3159791/result.docx).
And the reference template I use: [default.docx](https://github.com/tomduck/pandoc-fignos/files/3159807/default.docx)

**Comment by melaniewalsh** [comment]
Thanks for checking in, @tomduck. I'm also using a [custom style template](https://pandoc.org/MANUAL.html#custom-styles) for converting to docx, which I've modified to number all h2 headers. The specific use case is that I'm writing my dissertation and would like figure numbers that correspond to each chapter number.

**Comment by tomduck** [comment]
OK, neat.  I hadn't considered that possibility.  I just pushed out a new release of pandoc-fignos and friends that addresses this issue, both in code and documentation.

Thank you so much for your feedback, @gepcel and @melaniewalsh.  I have always wanted to better support docx, but it is difficult because I am not a docx user.  This Issue report explaining how users can number sections in docx and solving how to support figure numbering by section was really helpful.

Cheers,
Tom

**Comment by gepcel** [comment]
Solved by series of commits **Support for numbering by section.** in 
[fignos](https://github.com/tomduck/pandoc-fignos/commit/ba7aebc802921619cfcf6a3d05945ee513e2d68f), [xnos](https://github.com/tomduck/pandoc-xnos/commit/ea8645cf4e047c572c563d65e88a5e08e220e7a6), [tablenos](https://github.com/tomduck/pandoc-tablenos/commit/27eac43274277a895c6bffcfe782444fe19f7609), [eqnos](https://github.com/tomduck/pandoc-eqnos/commit/4b8b260301399d6555c411be44809cca7f0a61f1)

**Comment by melaniewalsh** [comment]
Thanks so much for your work on this, @tomduck 

I upgraded to the newest version of pandoc-fignos, but for some reason I'm still not getting figure numbering by section in my docx file. It's still numbering them but just not incorporating the section. I can't figure out what I might be doing wrong

**Comment by melaniewalsh** [comment]
Actually, I think I figured it out by including 'docx' in this line of pandoc_fignos.py:

`if numbersections and fmt in ['html', 'html5', 'docx'] and 'tag' not in kvs:`

This is what @gepcel did in one of his pull requests. Has that pull request been integrated into pandoc_fignos.py?

#60

**Comment by tomduck** [comment]
Rats.  Sorry I didn't get it right the first time.  I just pushed out pandoc-fignos 1.4.1.  This should correct the problem.  Once we are sure of it I will make the corresponding changes to pandoc-eqnos and pandoc-tablenos.  Thanks for your help.

**Comment by tomduck** [comment]
I'm assuming that this is no longer an issue.  Please re-open this issue if there are further difficulties.

Note that there is a new 2.0.0 branch which provides further improvements to epub output.

Thanks again for your feedback, which was helpful. ☺︎

Cheers,
Tom
